# Generated by Django 2.2.4 on 2019-08-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190828_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='website',
            field=models.URLField(),
        ),
    ]
