# Generated by Django 2.2.4 on 2019-08-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20190828_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='time',
        ),
        migrations.AddField(
            model_name='education',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
