# Generated by Django 2.2.4 on 2019-08-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190828_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
