# Generated by Django 2.2.4 on 2019-08-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190828_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='select',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
