# Generated by Django 2.2.4 on 2019-08-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_education_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='time',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
