# Generated by Django 2.2.4 on 2019-08-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_workexperience_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='select',
            field=models.BooleanField(),
        ),
    ]
