# Generated by Django 2.2.4 on 2019-08-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190828_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.CharField(default='defalt', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(default='hung.che.yi@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='phone',
            field=models.CharField(default=491721537025, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='website',
            field=models.CharField(default='http://jaythecheyi.pythonanywhere.com/', max_length=100),
            preserve_default=False,
        ),
    ]
