# Generated by Django 2.2.4 on 2019-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20190828_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
