# Generated by Django 2.2.3 on 2019-11-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_bigproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
